name: 'Example composite GitHub action'
description: 'Example composite GitHub action'
author: hello@cloudposse.com
branding:
  icon: 'file'
  color: 'white'
inputs:
  organization:
    required: true
    description: "Organization"
  api_key_id:
    required: true
    description: "API Key ID"
  api_key_secret:
    required: true
    description: "API Key Secret"
  stack:
    required: true
    description: "Stack"
    default: "true"
  github_token:
    required: true
    description: "GitHub Token (Required to install Spacelift CLI)"
outputs:
  outputs:
    description: "Stack outputs"
    value: "${{ steps.spacelift.outputs.result }}"
runs:
  using: "composite"
  steps:
    - name: Install spacectl
      uses: spacelift-io/setup-spacectl@main
      env:
        GITHUB_TOKEN: ${{ inputs.github_token }}

    - name: 'Setup jq'
      uses: dcarbone/install-jq-action@v1.0.0

    - id: spacelift
      name: Spacelift deploy
      shell: bash
      env:
        SPACELIFT_API_KEY_ENDPOINT: https://${{ inputs.organization }}.app.spacelift.io
        SPACELIFT_API_KEY_ID: ${{ inputs.api_key_id  }}
        SPACELIFT_API_KEY_SECRET: ${{ inputs.api_key_secret  }}
      run: |
        spacectl stack deploy --id=${{ inputs.stack }} --tail
        RESULT=$(spacectl stack outputs --id=${{ inputs.stack }} --no-color --output json | \
          jq 'map({id: .id, value: (.value | fromjson) })' -c -e -M
        )
        echo "result=${RESULT}" >> $GITHUB_OUTPUT
